yarnPath: '.yarn/releases/yarn-berry.js'
# @oswee:registry=https://npm.pkg.github.com

npmRegistryServer: 'https://npm.pkg.github.com'

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
    npmAuthToken: ${GITHUB_NPM_PAT}

npmScopes:
  oswee:
    npmRegistryServer: https://npm.pkg.github.com
    npmPublishRegistry: https://npm.pkg.github.com
    npmAlwaysAuth: false
    npmAuthToken: ${GITHUB_NPM_PAT}
  dzintars:
    npmRegistryServer: https://npm.pkg.github.com
    npmPublishRegistry: https://npm.pkg.github.com
    npmAlwaysAuth: false
    npmAuthToken: ${GITHUB_NPM_PAT}
