yarnPath: '.yarn/releases/yarn-berry.js'

npmRegistryServer: 'https://npm.pkg.github.com'
npmPublishRegistry: 'https://npm.pkg.github.com'

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
    npmAuthIdent: 'username:password'
    npmAuthToken: ${GITHUB_NPM_PAT}

npmScopes:
  dzintars:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_NPM_PAT}
  oswee:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmAlwaysAuth: false
    npmAuthToken: ${GITHUB_NPM_PAT}
